### ISSUE TITLE
Query on Open Targets Association Files

### ISSUE THREAD

**Issue by shaileshchaudhary11** [biocypher/open-targets#10]
I am working on creating a knowledge graph using data from the Open Targets Platform ([Open Targets Platform](https://platform.opentargets.org/downloads)). I have a specific question regarding the creation of edges between nodes. Could you clarify the meaning of the different association files available on the Open Targets Data Download Platform? I am including a screenshot of the datasets related to associations for reference. Your guidance on how these associations are defined and their significance would be greatly appreciated.

![image](https://github.com/user-attachments/assets/023be797-f374-4a50-899f-4ce0b8cf3f5d)

**Comment by slobentanzer** [comment]
Hi @shaileshchaudhary11, thanks for your interest. We are not (yet) very qualified for explaining Open Targets contents and semantics, that question is probably better directed at them. They have a GitHub org and a community platform as well. https://community.opentargets.org

Kind regards, Sebastian
