### ISSUE TITLE
Error when running generating neo4j compatible files

### ISSUE THREAD

**Issue by Kabenla** [biocypher/open-targets#14]
Somewhere between commit ec3617c834acae937cec930140fb746be3cd2c55 and the head of the main branch (f74bba0a9609bd7898e9a785bfa83b9e0949a769), an update of the dependencies has broken the cod so that when I run `poetry run python scripts/target_disease_script.py`, the script crashes with the error `ImportError: cannot import name 'ENCODERS_BY_TYPE' from 'pydantic.json'`

To fix this, I used the poetry.lock and  pyproject.toml from commit ec3617c834acae937cec930140fb746be3cd2c55 to replace those in the head of the main branch (f74bba0a9609bd7898e9a785bfa83b9e0949a769), rerun poetry install, and the target_disease_script.py started working properly again.

Below are the dependancies that got updated.  I got this list by resetting the poetry.lock and  pyproject.toml in the head of the main branch and running poetry install.

I think one or more of the updates below is breaking things

Package operations: 0 installs, 27 updates, 0 removals

  - Updating typing-extensions (4.6.3 -> 4.12.2)
  - Updating certifi (2023.5.7 -> 2024.8.30)
  - Updating charset-normalizer (3.1.0 -> 3.3.2)
  - Updating idna (3.4 -> 3.10)
  - Updating pytz (2023.3 -> 2024.2)
  - Updating urllib3 (2.0.3 -> 2.2.3)
  - Updating click (8.1.3 -> 8.1.7)
  - Updating colorlog (6.7.0 -> 6.8.2)
  - Updating numpy (1.25.0 -> 2.1.1)
  - Updating neo4j (4.4.11 -> 4.4.12)
  - Updating packaging (23.1 -> 24.1)
  - Updating pydantic (1.10.9 -> 2.9.2)
  - Updating pyparsing (3.1.0 -> 3.1.4)
  - Updating python-dateutil (2.8.2 -> 2.9.0.post0)
  - Updating pyyaml (6.0 -> 6.0.2)
  - Updating requests (2.31.0 -> 2.32.3)
  - Updating tqdm (4.65.0 -> 4.66.5)
  - Updating tzdata (2023.3 -> 2024.1)
  - Updating curies (0.5.5 -> 0.7.10)
  - Updating more-itertools (9.1.0 -> 10.5.0)
  - Updating networkx (3.1 -> 3.2.1)
  - Updating pandas (2.0.2 -> 2.2.2)
  - Updating pystow (0.5.0 -> 0.5.5)
  - Updating tornado (6.3.2 -> 6.4.1)
  - Updating biocypher (0.5.16 -> 0.5.44)
  - Updating isort (5.12.0 -> 5.13.2)
  - Updating pyspark (3.4.0 -> 3.5.2)

**Comment by slobentanzer** [comment]
Hi @Kabenla,
many thanks for the report, and for investigating the source. I am hesitant to lock a sub-dependency to a prior version, but the issue you identified is that we haven't updated the dependencies for a while (project was on hold).

I have updated some of the major dependencies in https://github.com/biocypher/open-targets/commit/fbd9b5f9f1d47cc304eb5340a821fd39bd974e38, which fixed the problem for me. Please try it with the most recent version (`0.2.1`) and let me know if that works for you, too.

**Comment by slobentanzer** [comment]
Hi @Kabenla,
can you please confirm the fix (and close the issue) at your convenience?

**Comment by slobentanzer** [comment]
Closing now, thanks for making us aware.
