### ISSUE TITLE
How to add new dataset like i want to add "Human Phenotype Ontology" using open-target.

### ISSUE THREAD

**Issue by shaileshchaudhary11** [biocypher/open-targets#7]
I want to add complete dataset from link "https://platform.opentargets.org/downloads" what are the file should i changed to achive this thing. I am using "https://github.com/biocypher/project-template" and "https://github.com/biocypher/open-targets" using this i able to see 6 databases in neo4j. Currently i am changing 3 files schema_config.yaml,target_disease_script.py and target_disease_evidence_adapter.py .

Below is log file generated by runnig target_disease_script.py file.
[biocypher-20240716-043436.log](https://github.com/user-attachments/files/16243290/biocypher-20240716-043436.log)

**Comment by slobentanzer** [comment]
Hi @shaileshchaudhary11,
apologies for the delay, I overlooked this issue.

Are you able to share your modified code? Without it, it is very hard to give an answer what's missing.

**Comment by slobentanzer** [comment]
Closing as stale
