### ISSUE TITLE
Trouble adding new association.

### ISSUE THREAD

**Issue by rahulmaurya1507** [biocypher/open-targets#8]
have successfully created nodes by adding more `open-targets` categories. However, I am now encountering difficulties with creating associations. The current setup, including the adapter and `schema_config.yml`, is configured by default to handle `gene to disease association`.

I am trying to introduce a new type of association, such as a `drug to gene association`, but I am unsure of the necessary updates to make this work. Specifically, I need guidance on the changes required in the `schema_config.yml`, `otar_biocypher/target_disease_evidence_adapter.py`, and `scripts/target_disease_script.py`. If additional files need to be created or other steps are required, I would appreciate any insights or advice you could provide to help me move forward.

**Comment by slobentanzer** [comment]
Hi @rahulmaurya1507,
thanks for the question. It would help me if you could clarify what you have already tried, did you follow the steps outlined in our tutorial for introducing new relationships? Are you getting any errors? Can you share any code?

**Comment by slobentanzer** [comment]
Hi @rahulmaurya1507,
do you still have this issue? Otherwise, feel free to close the issue. :)

**Comment by rahulmaurya1507** [comment]
I'm trying. Will have some results by tomorrow.

**Comment by slobentanzer** [comment]
Hi @rahulmaurya1507,
just a reminder to please update or close the issue.
